# Generated by Django 2.2 on 2019-08-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190801_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='hobbies',
            new_name='interests',
        ),
    ]
